# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos

###

# @name create-transcription
POST http://localhost:3333/videos/dsaj1eud913j199812je12j9/transcription
Content-Type: application/json
{
    "prompt": "clean arch, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json
{
    "videoId": "dsaj1eud913j199812je12j9",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da trancrição do vídeo informada a seguir: '''{transcription}'''"
}

